name: ocr_digitization_app_final
description: OCR-powered document digitization Flutter app.
publish_to: 'none' # This prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & State Management
  provider: ^6.1.1

  # HTTP Requests
  http: ^1.2.1

  # Image Picker (Camera/Gallery)
  image_picker: ^1.1.1

  # File Picker
  file_picker: ^10.2.0

  # File & Path Handling
  path_provider: ^2.1.3

  # Local Storage
  shared_preferences: ^2.2.3

  # Web Support (Clipboard, Downloads)
  universal_html: ^2.2.4

  # URL Launcher (for links if needed)
  url_launcher: ^6.2.6

  # ✅ Android Email Intent (Gmail integration)

  # ✅ Firebase Integration
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.7
  cloud_firestore: ^5.6.9
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/avatar.png
    - assets/logo.png
    - assets/google_logo.png
