// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBfETdv3WxewqrXRhpuv8VC-H8IRgZ5eE',
    appId: '1:171174008455:web:d77d7a08f5f24f7807ca22',
    messagingSenderId: '171174008455',
    projectId: 'ocr-digitization-platform',
    authDomain: 'ocr-digitization-platform.firebaseapp.com',
    storageBucket: 'ocr-digitization-platform.firebasestorage.app',
    measurementId: 'G-X5XRCWH6V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuL-HbWVGTQsORR_3fo3Vjm4uOhvM2Fuc',
    appId: '1:171174008455:android:b801afe52d3b1fe707ca22',
    messagingSenderId: '171174008455',
    projectId: 'ocr-digitization-platform',
    storageBucket: 'ocr-digitization-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0-NFVA0YPWJbdFf7JhL5CnXw70zRzFds',
    appId: '1:171174008455:ios:0dd857b04deca8fb07ca22',
    messagingSenderId: '171174008455',
    projectId: 'ocr-digitization-platform',
    storageBucket: 'ocr-digitization-platform.firebasestorage.app',
    androidClientId: '171174008455-ihpm5ugcpinfgg8fbjfv5bn6tc9v2m24.apps.googleusercontent.com',
    iosClientId: '171174008455-6orddmo6qjqo7f455bs74uqi4as1m791.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocrDigitizationNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0-NFVA0YPWJbdFf7JhL5CnXw70zRzFds',
    appId: '1:171174008455:ios:0dd857b04deca8fb07ca22',
    messagingSenderId: '171174008455',
    projectId: 'ocr-digitization-platform',
    storageBucket: 'ocr-digitization-platform.firebasestorage.app',
    androidClientId: '171174008455-ihpm5ugcpinfgg8fbjfv5bn6tc9v2m24.apps.googleusercontent.com',
    iosClientId: '171174008455-6orddmo6qjqo7f455bs74uqi4as1m791.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocrDigitizationNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBfETdv3WxewqrXRhpuv8VC-H8IRgZ5eE',
    appId: '1:171174008455:web:b816858aa0859d3c07ca22',
    messagingSenderId: '171174008455',
    projectId: 'ocr-digitization-platform',
    authDomain: 'ocr-digitization-platform.firebaseapp.com',
    storageBucket: 'ocr-digitization-platform.firebasestorage.app',
    measurementId: 'G-V1QJ7Y1W33',
  );
}
